# render.yaml
services:
  - type: web
    name: ecommerce
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildFilter:
      paths:
        - .
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"
